--- #YAML:1.0
name:                POE-Filter-Snort
version:             0.02
abstract:            POE stream filter for parsing Snort logs
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Rocco Caputo <rcaputo@cpan.org>
distribution_type:   module
requires:     
    POE:                           0.3101
    Test::More:                    0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
