# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Filter-Snort
version:      0.01
version_from: Snort.pm
installdirs:  site
requires:
    POE:                           0.3101
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.28
